-- Viewing Tables
--

SELECT * FROM Contacts;
SELECT * FROM Creates;
SELECT * FROM DNS;
SELECT * FROM DNS2;
SELECT * FROM Drafts;
SELECT * FROM NTP;
SELECT * FROM NTP2;
SELECT * FROM Received;
SELECT * FROM Receives;
SELECT * FROM Saves;
SELECT * FROM Sends;
SELECT * FROM Sent;
SELECT * FROM SSDP;
SELECT * FROM SSDP2;
SELECT * FROM Users;
SELECT * FROM AutoSend;
SELECT * FROM AutoReceive;
